apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.anfisa_front.name }}
  labels:
    app: {{ .Values.anfisa_front.name }}
  
spec:
  ports:
  - name: {{ .Values.anfisa_front.name }}
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.anfisa_front.name }}
  sessionAffinity: None
  type: ClusterIP