# Default values

# ------------------------------------------------------------------------------
# S3PVC-CLAIM:
#persistenceVolumeClaim for anfisa and druid-components
# ------------------------------------------------------------------------------

volumeclaim :
  bucket: forome-anfisa
  secret: cos-write-access
  # claim: s3pvc ----> #hardcode in PVC
  # access_mode: ReadWriteOnce ----> #hardcode in PVC
  # size: "1000Gi" #hardcode
  # storageclass: ibmc-s3fs-standard-regional ----> #hardcode in PVC

# ------------------------------------------------------------------------------
# Anfisa-ingress:
# ------------------------------------------------------------------------------
ingress:
  name: anfisa-ingress
  host: qa.asset-forome-0b8a4e8de101bcbaf4eafc441eda83b3-0000.us-south.containers.appdomain.cloud
  certificate: asset-forome-0b8a4e8de101bcbaf4eafc441eda83b3-0000
  #oc get secrets -n openshift-ingress - view secrets with TLC-certificates

# ------------------------------------------------------------------------------
# Anfisa-back:
# ------------------------------------------------------------------------------

anfisa:
  project: anfisa-qa
  name: anfisa-back
  git_uri: https://github.com/ForomePlatform/anfisa-openshift.git
  git_branch: master
  output_registry: image-registry.openshift-image-registry.svc:5000
  anfisa_volumes:
    workdir_volume: anfisa-workdir
    workdir_claim_name: anfisa-workdir-claim

# ------------------------------------------------------------------------------
# anfisa_front:
# 
anfisa_front:
  name: anfisa-front
  git_uri: https://github.com/evgeniyabrosin/Anfisa-React-Client-1.git
  git_branch: develop
  url_backend: qa.asset-forome-0b8a4e8de101bcbaf4eafc441eda83b3-0000.us-south.containers.appdomain.cloud/app/
  
# ------------------------------------------------------------------------------
# Annotator:
# ------------------------------------------------------------------------------

annotator:
  project: anfisa-qa
  name: annotation
  git_uri: https://github.com/evgeniyabrosin/Anfisa-Annotations.git
  # git_uri: https://github.com/nikita-kapishev/Anfisa-Annotations.git
  git_branch: docker-support
  output_registry: image-registry.openshift-image-registry.svc:5000
