apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.annotator.name }}
  labels:
    app: {{ .Values.annotator.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.annotator.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.annotator.name }}
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 0
        # fsUser: 999
        runAsUser: 0
      initContainers:
        - name: vep-config
          image: "{{ .Values.annotator.output_registry }}/{{ .Values.annotator.project }}/{{ .Values.annotator.name }}"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          stdin: true
          command:
            - "entrypoint.sh"
          args:
            - "configurevep"
          # serviceAccount: default
          volumeMounts:
          - name: vep-cache
            mountPath: /opt/vep/.vep/
      containers:
        - name: annotation
          image: "{{ .Values.annotator.output_registry }}/{{ .Values.annotator.project }}/{{ .Values.annotator.name }}"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          stdin: true
          command:
            - "entrypoint.sh"
          args:
            - "astorage"
          volumeMounts:
          - name: configs
            mountPath: /data/project/AStorage/astorage.cfg
            subPath: astorage.cfg
          - name: configs
            mountPath: /data/project/AStorage/config.json
            subPath: config.json
          - name: vep-cache
            mountPath: /opt/vep/.vep/
          # - name: anfisa-annotation-data
          #   mountPath: /data/forannotation/
          # - name: anfisa-annotation-db
          #   mountPath: /db/
          - name: data
            mountPath: /data/project/AStorage/rdbs/
            subPath: rdbs
          - name: data
            mountPath: /data/project/AStorage/schema/
            subPath: schema
          - name: data
            mountPath: /data/project/AStorage/venv/
            subPath: venv
          - name: forome-anfisa-s3
            mountPath: /data/anfisa/
          - name: forome-annotation-s3
            mountPath: /data/annotation
          
      volumes:
      - name: configs
        configMap:
          name: {{ .Values.annotator.name }}

      - name: vep-cache
        persistentVolumeClaim:
          claimName: annotation-pvc

      - name: data
        persistentVolumeClaim:
          claimName: forome-annotation-pvc

      - name: forome-anfisa-s3
        persistentVolumeClaim:
          claimName: forome-anfisa-s3-pvc

      - name: forome-annotation-s3
        persistentVolumeClaim:
          claimName: forome-annotation-s3-pvc

      # - name: anfisa-annotation-db
      #   persistentVolumeClaim:
      #     claimName: annotation-db-pvc


      terminationGracePeriodSeconds: 5