apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: forome-annotation-s3-pvc
  annotations:
    ibm.io/auto-create-bucket: "true"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: forome-annotation
    ibm.io/secret-name: forome-annotation-writer
spec:
  storageClassName: ibmc-s3fs-standard-regional
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1000Gi"

